import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ParticleConnectkit } from "@/context/Connectkit";
import Aurora from "@/components/aurora";
import Footer from "@/components/footer";

const geistSans = localFont({
   src: "./fonts/GeistVF.woff",
   variable: "--font-geist-sans",
   weight: "100 900",
});
const geistMono = localFont({
   src: "./fonts/GeistMonoVF.woff",
   variable: "--font-geist-mono",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="system"
               enableSystem
               disableTransitionOnChange
            >
               {/* <ParticleConnectkit> */}

               {/* <Aurora
                     colorStops={["#3A29FF", "#FF94B4", "#FF3232"]}
                     speed={0.2}
                  /> */}


               {children}
               <Footer />
               {/* </ParticleConnectkit> */}
            </ThemeProvider>

         </body>
      </html>
   );
}
